# vim ft=yaml
# CI on Windows via appveyor

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'

build_script:
  - nmake -f Makefile.win

test_script:
  - .\x86report

artifacts:
  - path: x86report.exe
